# Site settings
title: GeekSoc
author: "GeekSoc Admin Group"
email: contact@geeksoc.org
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "//127.0.0.1:4000"
twitter_username: strath_geeksoc
github_username:  GeekSoc

paginate: 5
paginate_path: "/posts/:num/"

committee_positions: [president, treasurer, comms, systems]
committee:
  president:
    name: Robert Wilson
    image: default.png
    email: president@geeksoc.org
    position: President
  treasurer:
    name: Eimantas Peckys
    image: default.png
    email: treasurer@geeksoc.org
    position: Treasurer
  systems:
    name: Adam McGhie
    image: default.png
    email: magic@geeksoc.org
    position: Systems Lead
  comms:
    name: Craig
    image: default.png
    email: comms@geeksoc.org
    position: Communications Officer

#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
markdown: rdiscount

# Continue compiling even if there are errors. Keep it true, unless troubleshooting.
auto: true

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: README.md, package.json, grunt.js, Gruntfile.js, node_modules, gen.sh, Gemfile
